name: "ASP Net Version Scanning"
description: "Scans the ASP.NET version in the repository"
inputs:
  urls:
    description: "List of URLs to scan"
    required: true
    type: array

runs:
  using: "composite"
  steps:
    - name: "ASP Net Version Scan"
      shell: bash
      run: |
        set -x
        for url in ${{ inputs.urls }}; do
          echo "Scanning URL: $url"
          url=$(echo "$url" | xargs | tr -d '\r')
          var=$(curl -s -I -k "$url" | grep -i "X-AspNet-Version" | cut -d ":" -f2 | xargs)
          if [ -n "$var" ]; then
            echo "$url - $var"
          else
            echo "$url - No X-AspNet-Version header found"
          fi
        done