name: "ASP Net Version Scanning"
description: "Scans the ASP.NET version in the repository"
inputs:
  Urls:
    description: "List of URLs to scan"
    required: true
    type: array

runs:
  using: "composite"
  steps:
    - name: "ASP Net Version Scan"
      shell: bash
      run: |
        for url in ${{ inputs.Urls }}; do
          echo "Scanning URL: $url"
          url=$(echo "$url" | xargs | tr -d '\r')
          var=$(curl -s -I -k "$url/<<" | findstr "X-AspNet-Version" | cut -d ":" -f2)
          echo "$url - $var"
        done